Adding hard failure for missing `BACKUP_NAME` env var Correcting missing usage of `BACKUP_NAME` in backup script Adding missing check in `test_crontab`

diff --git a/src/backup b/src/backup
--- a/src/backup
+++ b/src/backup
@@ -11,12 +11,12 @@ if [ -z "$MYSQL_ENV_MYSQL_HOST" ]; then echo "Error: MYSQL_ENV_MYSQL_HOST not se
 if [ -z "$MYSQL_ENV_MYSQL_USER" ]; then echo "Error: MYSQL_ENV_MYSQL_USER not set"; echo "Finished: FAILURE"; exit 1; fi
 if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]; then echo "Error: MYSQL_ENV_MYSQL_DATABASE not set"; echo "Finished: FAILURE"; exit 1; fi
 if [ -z "$MYSQL_ENV_MYSQL_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$BACKUP_NAME" ]; then export BACKUP_NAME=backup; fi
+if [ -z "$BACKUP_NAME" ]; then echo "Error: BACKUP_NAME not set"; echo "Finished: FAILURE"; exit 1; fi
 
 if [ -n "$CLEANUP_OLDER_THAN" ]; then cleanup;  fi
 
 echo 'creating backup archive of /var/www/html'
-tar --create --gzip -vv --directory="/var/www/html/" --file="/backups/backup_`date '+%Y%m%d'`.tar.gz" "./"
+tar --create --gzip -vv --directory="/var/www/html/" --file="/backups/${BACKUP_NAME}_`date '+%Y%m%d'`.tar.gz" "./"
 
 echo 'creating database dump'
 mysqldump -h $MYSQL_ENV_MYSQL_HOST --add-drop-table -u$MYSQL_ENV_MYSQL_USER -p $MYSQL_ENV_MYSQL_DATABASE --password=$MYSQL_ENV_MYSQL_PASSWORD | bzip2 -c > /backups/${BACKUP_NAME}_`date '+%Y%m%d'`.sql.bz2
diff --git a/src/restore b/src/restore
--- a/src/restore
+++ b/src/restore
@@ -13,7 +13,7 @@ if [ -z "$MYSQL_ENV_MYSQL_USER" ]; then echo "Error: MYSQL_ENV_MYSQL_USER not se
 if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]; then echo "Error: MYSQL_ENV_MYSQL_DATABASE not set"; echo "Finished: FAILURE"; exit 1; fi
 if [ -z "$MYSQL_ENV_MYSQL_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi
 if [ -z "$MYSQL_PORT_3306_TCP_PORT" ]; then echo "Error: MYSQL_PORT_3306_TCP_PORT not set"; echo "Finished: FAILURE"; exit 1; fi
-if [ -z "$BACKUP_NAME" ]; then export BACKUP_NAME=backup; fi
+if [ -z "$BACKUP_NAME" ]; then echo "Error: BACKUP_NAME not set"; echo "Finished: FAILURE"; exit 1; fi
 
 if ! [[ $1 =~ ^[a-zA-Z0-9_-]+$ ]]
 then
